### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by BronsonQuick**
@joehoyle I've brought in the upstream changes and kept the mods you have in our fork with the header statuses.

You'll probably want to do a good code review and test of this before you merge it in though.

### CODE REVIEW

**Comment by BronsonQuick** [comment]
@joehoyle Oh yeah, I also added links to the commits to the upstream repo in my commit messages for you as well so you can cross reference.

**Comment by joehoyle** [comment]
Hmm I'm trying to work out what commit the `use_stale` stuff came from.

**Comment by BronsonQuick** [comment]
@joehoyle It was this one: https://github.com/humanmade/batcache/commit/47ead937a30c871728373305c8120ff5d1feaf88 which was a terrible commit from upstream: https://github.com/Automattic/batcache/commit/c0c4182b5dc7618e11b0c36ccf68617a4b629557

Honestly

**Comment by joehoyle** [comment]
Ok cool, thanks a lot for handling @BronsonQuick !

**Pull request merged**
